### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Sehrishkhan33** [ZhangLin-PKU/FedFTG#4]
thank you for such a great work, i am trying to reproduce your work, and it goves me error on execuation: Traceback (most recent call last):
  File "/content/FedFTG/FedFTG/../train.py", line 6, in <module>
    from models import model_choose_fn
  File "/content/FedFTG/models/model_choose_fn.py", line 2, in <module>
    from models import simple_models
ImportError: cannot import name 'simple_models' from 'models' (unknown location)

**Comment by ZhangLin-PKU** [comment]
Hi @Sehrishkhan33 ,

You can just remove this line. I used other models what the "simple_models" library include during researching, but they are not used in the final model. I will remove this line later. Thank you for reminding me.

**Comment by wwwwww-ta** [comment]
thank you for such a great work, i am trying to reproduce your work, and it goves me error on execuation: Traceback (most recent call last):
  File "D:\联邦学习\知识蒸馏\代码\FedFTG-main\train.py", line 249, in <module>
    run(config)
  File "D:\联邦学习\知识蒸馏\代码\FedFTG-main\train.py", line 31, in run
    data_obj = util_dataset.DatasetObject(dataset=conf['dataset'],
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\联邦学习\知识蒸馏\代码\FedFTG-main\utils\util_dataset.py", line 29, in __init__
    self.clnt_x, self.clnt_y, self.tst_x, self.tst_y = self._load_split_data(seed, rule, rule_arg, unbalanced_sgm)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\联邦学习\知识蒸馏\代码\FedFTG-main\utils\util_dataset.py", line 207, in _load_split_data
    clnt_x, clnt_y = self._split_data(clnt_data_list, trn_x, trn_y, rule, rule_arg, sgm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\联邦学习\知识蒸馏\代码\FedFTG-main\utils\util_dataset.py", line 128, in _split_data
    clnt_x = np.asarray(clnt_x)
             ^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (100,) + inhomogeneous part.
